name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    environment:
      php: 7.4
    coverage:
      coverage:
        tests:
          override:
            - command: 'vendor/bin/phpunit tests --coverage-clover tests/clover.xml --configuration phpunit.xml'
              coverage:
                file: 'tests/clover.xml'
                format: 'clover'
  checks:
    php: true
  tools:
    php_cs_fixer: true
